services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: greenalert-mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"  # troque por uma senha forte
      MSSQL_PID: "Express"
      TZ: "America/Sao_Paulo"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql           # <— named volume (sem bind mount)
    healthcheck:
      test: ["CMD-SHELL", "bash -c '</dev/tcp/127.0.0.1/1433'"]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 20s
    restart: unless-stopped

volumes:
  mssql-data:
